### ISSUE TITLE
ModuleNotFoundError: No module named 'models.model_utils'

### ISSUE THREAD

**Issue by erichhhhho** [ianwhale/nsga-net#1]
ModuleNotFoundError: No module named 'models.model_utils'

**Comment by cwhuang888** [comment]
+1

**Comment by anonymone** [comment]
@ianwhale Can you solve this problem?

**Comment by iwhalen** [comment]
Thank you for mentioning me @anonymone, I forgot to turn on notifications for this repo. 
I added the missing file. Let me know if that works.

**Comment by anonymone** [comment]
It doesn't works.
Here is the error info when I run nsga2_main.py :
```ImportError: No module named 'config'```
and I try to install config module with 
```pip install config```
another problem occured.
```AttributeError: module 'config' has no attribute 'parser'```
@ianwhale

**Comment by iwhalen** [comment]
Hey again, I got in contact with @mikelzc1990 and he fixed our config problems. You should be able to run `nsga2_main.py` now. It is in a debugging mode so fitness of each network is randomly assigned rather than running a full backprop.

**Comment by mikelzc1990** [comment]
Please change the argument "--eval-method" to 0 to run the back-propagation on each model sampled. The back-propagation part of the code was developed under PyTorch 0.3. This is the preliminary version of NSGA-Net, we will upload the new version after the review process of our paper.

**Comment by anonymone** [comment]
> Hey again, I got in contact with @mikelzc1990 and he fixed our config problems. You should be able to run `nsga2_main.py` now. It is in a debugging mode so fitness of each network is randomly assigned rather than running a full backprop.

Thanks so much!
