### ISSUE TITLE
[ERROR REPORT] No module named 'config' 

### ISSUE THREAD

**Issue by anonymone** [ianwhale/nsga-net#3]
Hi, @ianwhale
Thanks for your great works on NAS and opening your codes.
Here is the error info :bug: when I run nsga2_main.py :
```ImportError: No module named 'config'```
and I try to install config module with
```pip install config```
another problem occured.
```AttributeError: module 'config' has no attribute 'parser'```

__Did I download wrong version of config or config is a missing python file?__

**Comment by iwhalen** [comment]
Fixed: #1
